import { ObjectId } from "mongodb";

const productIds = [
    new ObjectId("6445d7f1e4b0fd586f3fa100"),
    new ObjectId("6445d7f1e4b0fd586f3fa101"),
    new ObjectId("6445d7f1e4b0fd586f3fa102"),
    new ObjectId("6445d7f1e4b0fd586f3fa103"),
    new ObjectId("6445d7f1e4b0fd586f3fa104"),
    new ObjectId("6445d7f1e4b0fd586f3fa105"),
    new ObjectId("6445d7f1e4b0fd586f3fa106"),
    new ObjectId("6445d7f1e4b0fd586f3fa107"),
    new ObjectId("6445d7f1e4b0fd586f3fa108"),
    new ObjectId("6445d7f1e4b0fd586f3fa109"),
    new ObjectId("6445d7f1e4b0fd586f3fa10a"),
    new ObjectId("6445d7f1e4b0fd586f3fa10b"),
    new ObjectId("6445d7f1e4b0fd586f3fa10c"),
    new ObjectId("6445d7f1e4b0fd586f3fa10d"),
    new ObjectId("6445d7f1e4b0fd586f3fa10e"),
    new ObjectId("6445d7f1e4b0fd586f3fa10f"),
    new ObjectId("6445d7f1e4b0fd586f3fa110"),
    new ObjectId("6445d7f1e4b0fd586f3fa111"),
    new ObjectId("6445d7f1e4b0fd586f3fa112"),
    new ObjectId("6445d7f1e4b0fd586f3fa113"),
    new ObjectId("6445d7f1e4b0fd586f3fa114"),
    new ObjectId("6445d7f1e4b0fd586f3fa115"),
    new ObjectId("6445d7f1e4b0fd586f3fa116"),
    new ObjectId("6445d7f1e4b0fd586f3fa117")
  ];
  
  export default [
    // **Comida**
    {
      _id: productIds[0],
      name: "Arroz integral",
      description: "Arroz de grano largo, ideal para dietas saludables.",
      price: 25.5,
      stock: 100,
      category: "Comida",
      expirationDate: new Date('2025-12-31'),
      image: "arroz_integral.jpg",
      supplier: "Proveedor A",
    },
    {
      _id: productIds[1],
      name: "Aceite de oliva",
      description: "Aceite de oliva extra virgen para cocinar o aderezar.",
      price: 35.0,
      stock: 50,
      category: "Comida",
      expirationDate: new Date('2026-05-15'),
      image: "aceite_oliva.jpg",
      supplier: "Proveedor B",
    },
    {
      _id: productIds[2],
      name: "Harina de trigo",
      description: "Harina refinada de trigo para repostería y cocina.",
      price: 15.0,
      stock: 75,
      category: "Comida",
      expirationDate: new Date('2025-08-10'),
      image: "harina_trigo.jpg",
      supplier: "Proveedor C",
    },
  
    // **Electrónica**
    {
      _id: productIds[3],
      name: "Smartphone Samsung Galaxy",
      description: "Smartphone con cámara de 48 MP y pantalla AMOLED.",
      price: 799.99,
      stock: 25,
      category: "Electrónica",
      expirationDate: null,
      image: "smartphone_samsung.jpg",
      supplier: "Proveedor D",
    },
    {
      _id: productIds[4],
      name: "Laptop Dell Inspiron",
      description: "Laptop con procesador i5, 8GB de RAM y 256GB SSD.",
      price: 650.0,
      stock: 15,
      category: "Electrónica",
      expirationDate: null,
      image: "laptop_dell.jpg",
      supplier: "Proveedor E",
    },
    {
      _id: productIds[5],
      name: "Auriculares inalámbricos Bose",
      description: "Auriculares con cancelación de ruido.",
      price: 180.0,
      stock: 50,
      category: "Electrónica",
      expirationDate: null,
      image: "auriculares_bose.jpg",
      supplier: "Proveedor F",
    },
    {
      _id: productIds[6],
      name: "Smartwatch Xiaomi",
      description: "Reloj inteligente con monitoreo de actividad física.",
      price: 120.0,
      stock: 100,
      category: "Electrónica",
      expirationDate: null,
      image: "smartwatch_xiaomi.jpg",
      supplier: "Proveedor G",
    },
  
    // **Hogar**
    {
      _id: productIds[7],
      name: "Sofá de 3 plazas",
      description: "Sofá de tela gris con estructura de madera.",
      price: 350.0,
      stock: 20,
      category: "Hogar",
      expirationDate: null,
      image: "sofa.jpg",
      supplier: "Proveedor H",
    },
    {
      _id: productIds[8],
      name: "Juego de sábanas",
      description: "Juego de sábanas de algodón de 300 hilos.",
      price: 45.0,
      stock: 60,
      category: "Hogar",
      expirationDate: null,
      image: "sabanas.jpg",
      supplier: "Proveedor I",
    },
    {
      _id: productIds[9],
      name: "Lámpara de pie",
      description: "Lámpara de pie de estilo moderno con regulador de intensidad.",
      price: 80.0,
      stock: 40,
      category: "Hogar",
      expirationDate: null,
      image: "lampara_pie.jpg",
      supplier: "Proveedor J",
    },
  
    // **Ropa**
    {
      _id: productIds[10],
      name: "Camisa de hombre",
      description: "Camisa de algodón de corte slim fit.",
      price: 30.0,
      stock: 100,
      category: "Ropa",
      expirationDate: null,
      image: "camisa_hombre.jpg",
      supplier: "Proveedor K",
    },
    {
      _id: productIds[11],
      name: "Pantalón de mezclilla",
      description: "Pantalón de mezclilla para hombre, talla 32.",
      price: 40.0,
      stock: 75,
      category: "Ropa",
      expirationDate: null,
      image: "pantalon_mezclilla.jpg",
      supplier: "Proveedor L",
    },
    {
      _id: productIds[12],
      name: "Vestido de mujer",
      description: "Vestido de verano con estampado floral.",
      price: 50.0,
      stock: 30,
      category: "Ropa",
      expirationDate: null,
      image: "vestido_mujer.jpg",
      supplier: "Proveedor M",
    },
    {
      _id: productIds[13],
      name: "Chaqueta de cuero",
      description: "Chaqueta de cuero para hombre, color marrón.",
      price: 120.0,
      stock: 50,
      category: "Ropa",
      expirationDate: null,
      image: "chaqueta_cuero.jpg",
      supplier: "Proveedor N",
    },
  
    // **Limpieza**
    {
      _id: productIds[14],
      name: "Detergente líquido",
      description: "Detergente líquido concentrado para todo tipo de ropa.",
      price: 10.0,
      stock: 150,
      category: "Limpieza",
      expirationDate: new Date('2026-06-30'),
      image: "detergente_liquido.jpg",
      supplier: "Proveedor O",
    },
    {
      _id: productIds[15],
      name: "Desinfectante multiusos",
      description: "Desinfectante multiusos con fragancia a limón.",
      price: 8.0,
      stock: 200,
      category: "Limpieza",
      expirationDate: new Date('2025-11-20'),
      image: "desinfectante.jpg",
      supplier: "Proveedor P",
    },
    {
      _id: productIds[16],
      name: "Guantes de limpieza",
      description: "Guantes de goma para limpieza pesada.",
      price: 5.0,
      stock: 300,
      category: "Limpieza",
      expirationDate: null,
      image: "guantes_limpieza.jpg",
      supplier: "Proveedor Q",
    },
  ];
  